### ISSUE TITLE
Wrongly claimed infeasible model

### ISSUE THREAD

**Issue by apfelix** [ERGO-Code/HiGHS#1718] opened 2024-04-05 14:26 UTC
Hi Highs-Team,

I have a model that I'm pretty sure should be feasible, but Highs claims it's infeasible.

Model (I added the `.txt` extension, so github allows the upload): 
[highs171_problem.lp.txt](https://github.com/ERGO-Code/HiGHS/files/14885963/highs171_problem.lp.txt)

I tried to solve the model via the python interface (not sure if that's relevant). Version `highspy==1.7.1_dev1` as well as the version build from the current `latest` (commit `51dea53f`) claim infeasible, while version `highspy==1.5.3` gives the following solution (again added the `.txt` extension, printed using `writeSolution` and `style=1` from version `1.5.3`)
[solution.sol.txt](https://github.com/ERGO-Code/HiGHS/files/14886059/solution.sol.txt)

I'm pretty sure about version `1.5.3` being right, a) from the way I build the model (I solved for another objective [maximizing] and creating this model as copy with an additional constraint `<other objective> >= <other optimal solution value> - tolerance_epsilon`, so the solution of the other model should be feasible here as well), and b) since CBC and SCIP agree with version `1.5.3`.

PS: Thanks for the great job in general in providing a well-performing freely usable solver :slightly_smiling_face:

**Comment by jajhall** [comment] 2024-04-05 14:38
I've reproduced the behaviour with `latest`, and note that with `presolve=off` HiGHS gets a solution with the optimal objective value of `-4052.7422`. 

There are bugs in presolve to be fixed. I'd just started work on #1710 when your message came in. The fact that v1.5.3 gives the right answer (with presolve) isn't surprising, as bugs have been fixed since v1.5.3, leading to presolve running differently, with the possibility of other bugs being exposed....

#1710 is a MIP with only 5 variables and 3 constraints, so you'll forgive me if that's more attractive than your `806 rows; 544 cols; 2298 nonzeros; 54 integer variables`

Thanks for your kind words: HiGHS is so satisfying to have developed

**Comment by fwesselm** [comment] 2024-04-22 13:40
This seems to be fixed by #1730 as well.

**Comment by apfelix** [comment] 2024-04-30 12:49
FYI: the problem no longer consists in `latest`

**Closed** 2024-04-30 12:53 UTC
Labels: MIP, bug, MIP Presolve
