### ISSUE TITLE
Setting  D_ITERATOR_DEBUG_LEVEL=0 under Windows generate conflicts for using HiGHS as a dependency

### ISSUE THREAD

**Issue by Downsite** [ERGO-Code/HiGHS#1129] opened 2023-02-03 08:02 UTC
The change that was added in a126bc8, is causing some issues for me.

I am trying to build HiGHS as part of a larger CMake project.

` LNK2038 : mismatch detected for '_ITERATOR_DEBUG_LEVEL'`

This is caused by the project being built in Debug Mode. This will set the flag to 2 by default, but HiGHs overwrites this setting locally.

I would like to be able to choose if this flag is set as a CMake option.

**Comment by jajhall** [comment] 2023-02-03 11:21
Am I correct in thinking that `_ITERATOR_DEBUG_LEVEL`has a default value of 0, and a fix for the issue is that if HiGHS finds that it's set to something else it should not set it to 2?

**Comment by Downsite** [comment] 2023-02-03 11:56
In Debug mode 2 is the default value. So I think there would not be any value defined during the CMake run.
See here (https://learn.microsoft.com/en-us/cpp/standard-library/iterator-debug-level?view=msvc-170).

**Comment by jajhall** [comment] 2023-02-03 12:35
So, you're saying that you want to use the default value, and the problem is that we're using a different value. @lgottwald will have done this for good reason - to speed up debug runs when checking for other issues.

For me, the solution is to comment out our local setting, and just remember that it might be useful to use it when we're developing HiGHS.

**Comment by Downsite** [comment] 2023-02-03 14:39
Yes, since other packages seem to be built with level 2 in mind. At least we have some issues with prebuilt libraries (specifically CPLEX) building their debug binaries with level 2.

However, I see the benefit of faster compilation.  
For me, it could be part of (or work similarly to) the FAST_BUILD option.

**Comment by jajhall** [comment] 2023-02-03 14:43
So, you're suggesting that the HiGHS setting of `_ITERATOR_DEBUG_LEVEL` is something that a user can define - like `FAST_BUILD`?

**Comment by jajhall** [comment] 2023-02-06 10:46
Fixed when #1135 is pushed to `latest`

**Comment by jajhall** [comment] 2023-02-06 11:09
Hmmm... it looks as if not setting `D_ITERATOR_DEBUG_LEVEL=0` causes problems on Windows.

I'll try to investigate

**Comment by jajhall** [comment] 2023-02-07 12:51
The continuous integration failures on Windows if `D_ITERATOR_DEBUG_LEVEL` is not set to zero can't be serious, since the tests pass on Linux/Mac. However, I wanted to get to the bottom of them.

I spent 2-3 hours yesterday failing to get Visual Studio to run in debug so that I could instigate.

Until I can make progress on this, I've no option but to set `D_ITERATOR_DEBUG_LEVEL=0`, sorry

**Comment by jajhall** [comment] 2023-02-13 09:05
Interesting, we used to get Windows failures due to passing entry `[0]`of a vector that might have size zero, but setting `D_ITERATOR_DEBUG_LEVEL=0` is masking them. Thanks for suggesting the use of `data()` rather than `&vector[0]`. It does look more elegant (to me!) and is observed to be [preferable](https://stackoverflow.com/questions/10740094/stdvector-vec-data-or-vec0).

**Comment by jajhall** [comment] 2023-02-13 14:00
Thanks for exposing the error in the `Factor-dense-tran` test. I've fixed this. I tried `-D_GLIBCXX_DEBUG` on Linux but it didn't give any errors. The good news is that Visual Studio is now allowing me to debug on my Windows laptop, and I've exposed another Windows-only failure.

**Comment by jajhall** [comment] 2023-02-14 17:51
Without setting `D_ITERATOR_DEBUG_LEVEL=0`, branch `fix-958` runs fine for `unit-tests.exe` in Visual Studio on Windows. I the CI tests on #1159 pass, then I'll merge `fix-1129` into `latest`, and close this issue.

**Comment by jajhall** [comment] 2023-02-20 09:10
`fix-1129` now merged into `latest`, and will propagate to master in due course and appear in `v1.5.0`

**Closed by jajhall** 2023-02-20 09:10 UTC
