### ISSUE TITLE
Does Highs invoke the underlying parallel dual simplex algorithm for mixed-integer problems

### ISSUE THREAD

**Issue by tu3256076** [ERGO-Code/HiGHS#1033] opened 2022-12-07 03:26 UTC

**Comment by odow** [comment] 2022-12-07 03:31
No. This is a duplicate of your question: https://github.com/ERGO-Code/HiGHS/issues/1030.

If you have further questions, you should open a discussion instead: https://github.com/ERGO-Code/HiGHS/discussions. The GitHub issues are for bug reports and feature requests.

**Comment by tu3256076** [comment] 2022-12-07 07:31
> No. This is a duplicate of your question: #1030.
> 
> If you have further questions, you should open a discussion instead: https://github.com/ERGO-Code/HiGHS/discussions. The GitHub issues are for bug reports and feature requests.

If I want to know the principle of MIP problem solving in HIGS, is there any related public papers or documents? I did not find author Leona Gottwald's rationale paper for this part of the implementation.Thanks again.

**Comment by odow** [comment] 2022-12-07 19:30
As far as I know, this is not documented anywhere. The source code is public and MIT licensed, which should be sufficient.

**Closed** 2022-12-07 22:15 UTC

**Comment by jajhall** [comment] 2022-12-08 07:15
> Do you know if HIGHS uses multithreading in solving MIP problems（not simplex）

Not yet
