### ISSUE TITLE
Memory leaks when using the C API

### ISSUE THREAD

**Issue by ggeog89** [ERGO-Code/HiGHS#778] opened 2022-03-23 18:55 UTC
Hi everyone!

I am trying to solve a production scheduling problem using HiGHS within an MFC VC++ application.
The good news is that HiGHS works fine and I am getting optimal solutions pretty fast. However, I found out that I am getting some 
serious memory leaks. I found out that these memory leaks occur only when I am calling the Highs_mipCall function (when I comment it out no leaks are detected). My code is based on the example "call_highs_from_c.c", however, no leaks are found on that file. The only major difference is that I am using new instead of malloc. Do you have any idea why I am getting these memory leaks? Could it be the fact that I am using new? Or maybe because I am using dynamic arrays instead of static arrays for variables like a_start, a_index etc.? 
You can find my code here: https://github.com/ggeog89/CTimeMinimization.git

Thank you!

**Comment by ggeog89** [comment] 2022-03-24 14:58
Actually, I am having memory leak issues even when I am running the "call_highs_from_c.c" file!
What I find weird is that when I am running "call_highs_from_c.c" in 64-bit I am getting no issues. However, when I am running it in 32-bit (I want to incorporate HiGHS into a 32-bit application) I am getting several memory leaks (see the attached .txt file). 
[DebugOutputLeaks.txt](https://github.com/ERGO-Code/HiGHS/files/8342605/DebugOutputLeaks.txt)
Again I haven't changed anything in the code, I am just running the code that is provided in the examples folder.
Do you have any idea why I am getting these memory leaks?

**Comment by ggeog89** [comment] 2022-04-06 20:02
I was wondering if you found the time to check this issue. I would like to use the solver for a model that I incorporated into a 32-bit commercial application. Unfortunately, these memory leaks make it impossible to continue with the deployment of this solution (at least using the HiGHS solver). Did you also identify the existence of these leaks? Do you have any particular time plan for the resolution of this issue?  
Thank you!

**Comment by jajhall** [comment] 2022-04-06 21:56
@lgottwald has fixed one via #782 and will address the others in due course.

**Comment by ggeog89** [comment] 2022-04-07 06:39
Great!

**Comment by lgottwald** [comment] 2022-04-08 08:24
Actually all the leaks are fixed. There is now only unfreed memory due to global scheduler data which is not leaked but kept for future calls to HiGHS. There is a function `HighsTaskExecutor::shutdown()` (include `parallel/HighsTaskExecutor.h`), which can only be accessed via C++ right now and is not yet integrated in any public interface. This function will make sure that all threads are signaled to exit and all memory of the global scheduler in HiGHS is released. It currently does not block to wait for the threads to exit so it may still be possible to reach the end of the program while another thread is running and holds unfreed memory, but when the function exits the previously created threads will exit as soon the operating system schedules them in and when the last thread exits it will free the memory held by the global scheduler. So when part of an application that continues to run after HiGHS has been called there is no need to block and the shutdown function should only be called if there will be no more calls to HiGHS in the future or when it is desired to change the number of threads that HiGHS should use in the next call.

In a future HiGHS version I will add a function to the C-API which internally calls the shutdown function and has a bool parameter to indicate whether the call should block until all threads are finished. Blocking is usually not required and only may be useful for debugging purposes to check that there is no memory allocated after the call.

In the code you sent, however, there are memory leaks not caused by HiGHS:

There is a break out of the for loop before the data is freed with
delete calls, this needs to be moved at the end of the loop.

Second issue is the missing return statement. This causes
undefined behavior and the compiler may assume that the end of the
function is never reached, because if it would be reached there is no
return which is undefined behavior. It can then apply optimizations under this assumption. So there
must be a return 0.

**Closed by lgottwald** 2022-04-08 08:24 UTC
Labels: bug

**Comment by jajhall** [comment] 2022-04-08 09:58
Thanks for this @lgottwald
