### ISSUE TITLE
Issues with small problems solved by HiGHS as external process on Windows

### ISSUE THREAD

**Issue by MikeSteglich** [ERGO-Code/HiGHS#1137] opened 2023-02-08 11:49 UTC
I have problems running small problems with HiGHS as an external process. It seems that HiGHS sometimes does not terminate when small problems are solved several times within an algorithm. It does not matter whether HiGHS is executed by C++ code with `popen` or Python via `subProcess.Popen`. (I know, that I could use the C++ or Python APIs ... but I want to run it this way.)

This problem occur on Windows with the binaries (HiGHS.v1.4.2.x86_64-w64-mingw32-cxx11.tar) provided my the Julia team @odow .  Similar tests on macOS with HiGHSstatic.v1.4.2.x86_64-apple-darwin and a self compiled binary (Master 1.5.0 B3381829e) ran successfully without any problems.

The problem can be reproduced with the following simple (and stupid) python script.
```
import subprocess

cmd = []
cmd.append("highs.exe")
#cmd.append("--options_file" )
#cmd.append("highs.opt")
cmd.append("diet-1.mps")

n=0
maxTest=50

while n < maxTest:    
    p = subprocess.Popen(cmd, stdout=subprocess.PIPE, stderr=subprocess.PIPE, universal_newlines=True) 
    
    while True:
        line = p.stdout.readline()
        if line:
            print(line)                
        else:
            break

    if p.wait() != 0:
        print(p.stderr.read())

    n+=1
    print('#########', n)
```
If  `time.sleep(0.05)` is included after `p.wait()`, the script runs without problems.

I tried the same script with Scip without any issues.

**Comment by MikeSteglich** [comment] 2023-02-08 14:47
[testHighs.zip](https://github.com/ERGO-Code/HiGHS/files/10686719/testHighs.zip)

**Comment by MikeSteglich** [comment] 2023-02-08 16:40
Update ... same issue with self-compiled HiGHS-Master on Windows ... 
The problem also occurs when `time.sleep()` is used.

**Comment by jajhall** [comment] 2023-02-08 22:02
We've had #1044 recently, but this was only when using compiled binaries, not self-compiled HiGHS

I'll try to reproduce your issue, but if it's only exposed on Windows, I can't see us being able to address it at present.

**Comment by MikeSteglich** [comment] 2023-02-09 13:10
In the meantime, I have tried three different self-compiled versions (MINGW64, UCRT64 and CLANG64) without success.

In all cases, the code in app\RunHiGHS.cpp is executed until `return (int)run_status;`. The destructor of the HiGHS class is also completely executed. However, highs.exe is still running and has memory in use.

`abort()` instead of `return (int)run_status;` works ... but cannot be the solution ;-)

**Comment by jajhall** [comment] 2023-02-09 13:58
So, maybe it's the same issue. When it was only an issue with the compiled binaries, debugging is next to impossible, as we don't manage the creation of the binaries.

Unfortunately the HiGHS team is very much Linux/MacOS minded, so our experience of identifying why things go wrong on Windows is very limited.

**Comment by jajhall** [comment] 2023-02-09 16:06
Thanks, that's so useful to know! When "it works on Linux/MacOS but not Windows" we're struggling

**Comment by MikeSteglich** [comment] 2023-02-09 16:11
I am in a similar situation. I am one of two of the CMPL team. We create mainly code on Linux and macOS. An I am the one who has to debug on Windows. Sometimes it drives me crazy.

**Comment by odow** [comment] 2023-12-08 01:16
Closing as a duplicate of #1044. I've just seen this happen as well.

**Closed by odow** 2023-12-08 01:16 UTC
